kubernetesClusterDomain: cluster.local
monitorBackend:
  monitorBackend:
    env:
      port: "8081"
    image:
      repository: ghcr.io/torchiaf/critik8s/monitor-backend
      tag: latest
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  replicas: 1
  type: ClusterIP
