apiVersion: v1
kind: ConfigMap
metadata:
  name: data-collector
data:
  AMQP_HOST: {{ .Values.amqpProxy.externalService.host }}
  AMQP_PORT: ""
  AMQP_USERNAME: {{ .Values.settings.rabbitmq.username }}
  AMQP_PASSWORD: {{ .Values.settings.rabbitmq.password }}
  ROUTE_1: {{ .Values.settings.rabbitmq.routing.key1 }}
  ROUTE_3: {{ .Values.settings.rabbitmq.routing.key3 }}
  ROUTE_4: {{ .Values.settings.rabbitmq.routing.key4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-backend
  labels:
  {{- include "monitor-backend.labels" . | nindent 4 }}
data:
  AMQP_HOST: {{ .Values.amqpProxy.externalService.host }}
  AMQP_PORT: ""
  AMQP_USERNAME: {{ .Values.settings.rabbitmq.username }}
  AMQP_PASSWORD: {{ .Values.settings.rabbitmq.password }}
  AMQP_PROXY_PATH: {{ .Values.settings.amqpProxy.path }}
  ROUTE_1: {{ .Values.settings.rabbitmq.routing.key1 }}
  ROUTE_2: {{ .Values.settings.rabbitmq.routing.key2 }}
  ROUTE_4: {{ .Values.settings.rabbitmq.routing.key4 }}
