apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-backend
  labels:
  {{- include "monitor-backend.labels" . | nindent 4 }}
data:
  rmq_username: {{ .Values.settings.rabbitmq.username }}
  rmq_password: {{ .Values.settings.rabbitmq.password }}
  rmq_relay: {{ .Values.settings.rmqRelay.path }}
