apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-backend
  labels:
    app: monitor-backend
  {{- include "monitor-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.monitorBackend.replicas }}
  selector:
    matchLabels:
      app: monitor-backend
    {{- include "monitor-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: monitor-backend
      {{- include "monitor-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PORT
          value: {{ quote .Values.monitorBackend.monitorBackend.env.port }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: monitor-backend
        image: {{ .Values.monitorBackend.monitorBackend.image.repository }}:{{ .Values.monitorBackend.monitorBackend.image.tag
          | default .Chart.AppVersion }}
        name: monitor-backend
        resources: {}
