apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-operator
  labels:
  {{- include "rabbitmq-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operator.serviceAccount.annotations | nindent 4 }}