apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  labels:
  {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cluster.replicas }}
  resources:
    requests:
      cpu: {{ .Values.cluster.resources.cpu }}
      memory: {{ .Values.cluster.resources.memory }}
    limits:
      cpu: {{ .Values.cluster.resources.cpu }}
      memory: {{ .Values.cluster.resources.memory }}
  rabbitmq:
    additionalConfig: |
      log.console.level = {{ .Values.rabbitmq.config.logLevel }}
      channel_max = 700
      default_user= {{ .Values.settings.rabbitmq.username }}
      default_pass = {{ .Values.settings.rabbitmq.password }}
      default_user_tags.administrator = true
  service:
    type: LoadBalancer
